services: 
  database: 
    image: postgres:latest 
    restart: always 
    environment: 
      POSTGRES_PASSWORD: verySecretPassword
      POSTGRES_USER: administrator
      POSTGRES_DB: todo 
    volumes: 
      - ./data/db:/var/lib/postgresql/data
  app:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6400/api/v1/health"]
      interval: 10s
      retries: 5
      start_period: 30s
    build: . 
    restart: always 
    environment: 
      SQLALCHEMY_DATABASE_URI: "postgresql://administrator:verySecretPassword@database:5432/todo" 
    ports: 
      - "6400:6400" 
    depends_on: 
      - database
